name = "hello-friend-trx"
license = "MIT"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "nect"

[original]
  name = "hello-friend-ng"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend"
